### ISSUE TITLE
Cant install Datashader

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/datashader#1018]
Ubuntu 20.04
Python 3.7.3

Running `pip install datashader`

```
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba, datashader
  Running setup.py install for llvmlite ... error
    Complete output from command /home/itamar/.pyenv/versions/3.7.3/envs/MOD/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3b1fhg54/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-spmncebw/install-record.txt --single-version-externally-managed --compile --install-headers /home/itamar/.pyenv/versions/3.7.3/envs/MOD/include/site/python3.7/llvmlite:
    running install
    running build
    got version from file /tmp/pip-install-3b1fhg54/llvmlite/llvmlite/_version.py {'version': '0.37.0', 'full': 'd77dc1bcdb5af040c549f4d1ceeb4db7c8d08718'}
    running build_ext
    /home/itamar/.pyenv/versions/3.7.3/envs/MOD/bin/python3.7 /tmp/pip-install-3b1fhg54/llvmlite/ffi/build.py
    LLVM version... 10.0.0
    
    Traceback (most recent call last):
      File "/tmp/pip-install-3b1fhg54/llvmlite/ffi/build.py", line 220, in <module>
        main()
      File "/tmp/pip-install-3b1fhg54/llvmlite/ffi/build.py", line 210, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-3b1fhg54/llvmlite/ffi/build.py", line 172, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 11.x.x, got '10.0.0'. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
```

**Comment by jbednar** [comment]
It looks from the messages like you'd need to install LLVM>11.0.0; have you tried that?

**Comment by ItamarShDev** [comment]
Yes. And it keeps failing

**Comment by jbednar** [comment]
Seems like the messages ought to change if LLVM>11.0.0 is installed; can you post the new messages?  If you still get the messages above, it's presumably failing to find the right LLVM installation.

**Comment by maximlt** [comment]
Closing, feel free to reopen with the full details if it's still an issue! :)
