### ISSUE TITLE
datashader examples fails; requests not installed?

### ISSUE THREAD

**Issue by wiseman** [holoviz/datashader#1047]
#### ALL software version info
```
macOS 12.1
Python 3.9.5
datashader==0.13.0
```

#### Description of expected behavior and the observed behavior

I did the following:

```
pip install datashader
datashader examples
```

And got this error:

```
Downloading NYC Taxi Data 1 of 1
Traceback (most recent call last):
  File "/Users/wiseman/data/adsbx/time-series/code/env/bin/datashader", line 8, in <module>
    sys.exit(main())
  File "/Users/wiseman/data/adsbx/time-series/code/env/lib/python3.9/site-packages/datashader/__main__.py", line 9, in main
    return pyct.cmd.substitute_main('datashader',args=args)
  File "/Users/wiseman/data/adsbx/time-series/code/env/lib/python3.9/site-packages/pyct/cmd.py", line 455, in substitute_main
    args.func(args) if hasattr(args,'func') else parser.error("must supply command to run")
  File "/Users/wiseman/data/adsbx/time-series/code/env/lib/python3.9/site-packages/pyct/cmd.py", line 394, in <lambda>
    parser.set_defaults(func=lambda args: fn(name, **{k: getattr(args,k) for k in vars(args) if k!='func'} ))
  File "/Users/wiseman/data/adsbx/time-series/code/env/lib/python3.9/site-packages/pyct/cmd.py", line 39, in examples
    fetch_data(name,path,require_datasets=False,use_test_data=use_test_data,force=force)
  File "/Users/wiseman/data/adsbx/time-series/code/env/lib/python3.9/site-packages/pyct/cmd.py", line 354, in fetch_data
    _process_dataset(d, output_dir, path, use_test_data=use_test_data, force=force)
  File "/Users/wiseman/data/adsbx/time-series/code/env/lib/python3.9/site-packages/pyct/cmd.py", line 325, in _process_dataset
    _url_to_binary_write(url, output_path, running_title)
  File "/Users/wiseman/data/adsbx/time-series/code/env/lib/python3.9/site-packages/pyct/cmd.py", line 233, in _url_to_binary_write
    resp = requests.get(url, stream=True)
AttributeError: 'NoneType' object has no attribute 'get'
```
I then did `pip install requests` and that resolved the error and allowed me to successfully run `datashader examples`

**Comment by ianthomas23** [comment]
I have confirmed this still occurs using the latest datashader 0.14.1 on both Linux and macOS. `requests` needs to be a compulsory dependency of `datashader` installs.
